// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"QPlus","status":true,"description":"<QPlus> (Should go above all Q Plugins)\r\nSome small changes to MV for easier plugin development.","parameters":{"Quick Test":"true","Default Enabled Switches":""}},
{"name":"QUpdate","status":true,"description":"<QUpdate>\r\nChecks QPlugins for updates","parameters":{}},
{"name":"QuasiMovement","status":false,"description":"v1.299\nChange the way RPG Maker MV handles Movement.\n<QuasiMovement>","parameters":{"Grid":"1","Off Grid":"false","Tile Size":"48","=====================":"","Smart Move":"3","Old Smart Move Dir":"false","Mid Pass":"false","Move On Click":"false","Diagonal":"true","Diagonal Speed":"0","Collision":"#ff0000","Water Collision":"#00ff00","Deep Water Collision":"#0000ff","Collision Map Scan":"4","Water Terrain Tag":"1","Deep Water Terrain Tag":"2","Player Box":"36, 24, 6, 24","Event Box":"36, 24, 6, 24","Boat Box":"36, 24, 6, 12","Ship Box":"36, 24, 6, 24","Airship Box":"36, 36, 6, 6","JSON folder":"data/","Collision Map folder":"img/parallaxes/","Region Map folder":"img/parallaxes/","Use Regions Boxes":"false","Show Boxes":"true","Draw Tile Boxes":"true","Cache Colliders as Bitmap":"true"}},
{"name":"QMovement-dev","status":false,"description":"<QMovement>\r\nDevelopment","parameters":{"Grid":"1","Tile Size":"48","Off Grid":"true","=================":"","Smart Move":"0","Mid Pass":"false","Move on click":"true","Diagonal":"true","Diagonal Speed":"0","Player Collider":"box, 36, 24, 6, 24","Event Collider":"box, 36, 24, 6, 24","Show Colliders":"true"}},
{"name":"QMovement","status":false,"description":"<QMovement>\r\nDevelopment","parameters":{"Grid":"1","Tile Size":"48","Off Grid":"true","=================":"","Smart Move":"2","Mid Pass":"false","Diagonal":"true","Diagonal Speed":"0","Player Collider":"box, 36, 24, 6, 24","Event Collider":"box, 36, 24, 6, 24","Show Colliders":"true"}},
{"name":"========================","status":false,"description":"","parameters":{}},
{"name":"QTouch","status":true,"description":"<QTouch>\nBetter mouse handling for MV","parameters":{"Mouse Decay":"60","Default Cursor":"icon/cursor-default.png","Pointer Cursor":"icon/cursor-pointer.png"}},
{"name":"========================","status":false,"description":"","parameters":{}},
{"name":"QInput","status":true,"description":"<QInput>\r\nAdds additional keys to Input class, and allows remapping keys.","parameters":{"Ok":"#enter, #space, #z, $A","Escape / Cancel":"#esc, #insert, #x, #num0, $B","Menu":"$Y","Shift":"#shift, #cancel, $X","Control":"#ctrl, #alt","Tab":"#tab","Pageup":"#pageup, #q, $L1","Pagedown":"#pagedown, #w, $R1","Left":"#left, #num4, $LEFT","Right":"#right, #num6, $RIGHT","Up":"#up, #num8, $UP","Down":"#down, #num2, $DOWN","Debug":"#f9","===========":"","FPS":"f2","Streched":"f3","FullScreen":"f4","Restart":"f5","Console":"f8"}},
{"name":"QInputRemap","status":false,"description":"<QInputRemap>\r\nQuasi Input Addon: Adds Key remapping to Options menu","parameters":{"Hide Keys":"","Disable Keys":"ok, escape","===========":"","Vocab: Ok":"Action","Vocab: Escape":"Cancel","Vocab: Shift":"Run","Vocab: Control":"Control","Vocab: Tab":"Tab","Vocab: Pageup":"Next","Vocab: Pagedown":"Prev","Vocab: Up":"Up","Vocab: Down":"Down","Vocab: Left":"Left","Vocab: Right":"Right"}},
{"name":"QNameInput","status":false,"description":"<QNameInput>\r\nQuasi Input addon: Adds Keyboard Input to Name Input Scene","parameters":{"Show Window with Keys":"false","Window Width":"480"}},
{"name":"========================","status":false,"description":"","parameters":{}},
{"name":"QSprite","status":true,"description":"<QSprite>\r\nLets you configure Spritesheets","parameters":{"File Name Identifier":"%{config}-","Random Idle Interval":"60 300","Use New Adjust":"true"}},
{"name":"QAudio","status":true,"description":"<QAudio>\r\nFew new audio features","parameters":{"Default Radius":"5","Default Max Volume":"100"}},
{"name":"QSpeed","status":true,"description":"<QSpeed>\r\nAllows for custom Move speeds and an acceleration effect","parameters":{"Acceleration":"true","Duration":"30"}},
{"name":"QCamera","status":true,"description":"<QCamera>\r\nBetter Camera control","parameters":{"Offset":"0.5","Shift Y":"0","Shift X":"0"}},
{"name":"QYScale","status":true,"description":"<QYScale>\r\nChange characters scale based off their Y value","parameters":{}},
{"name":"QMap","status":true,"description":"<QMap>\r\ndesc","parameters":{"":""}},
{"name":"========================","status":false,"description":"","parameters":{}},
{"name":"QImport","status":true,"description":"<QImport>\r\ndesc","parameters":{"":""}},
{"name":"QPathfind","status":true,"description":"<QPathfind>\r\ndesc","parameters":{"":""}}
];
